/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "guizhanlib"
include(":guizhanlib-slimefun")
include(":guizhanlib-updater")
include(":guizhanlib-api")
include(":guizhanlib-common")
include(":guizhanlib-localization")
include(":guizhanlib-minecraft")
