/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.guizhanss.java-conventions")
}

dependencies {
    providedCompile(project(":GuizhanLib-common"))
    providedCompile(project(":GuizhanLib-minecraft"))
}

description = "GuizhanLib-localization"
