/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.guizhanss.java-conventions")
}

dependencies {
    api(project(":GuizhanLib-common"))
    api(project(":GuizhanLib-localization"))
    api(project(":GuizhanLib-minecraft"))
    api(project(":GuizhanLib-slimefun"))
    api(project(":GuizhanLib-updater"))
}

description = "GuizhanLib-api"
